#@data/values
---
ingress:
  domain: <INGRESS-DOMAIN>
  contour_tls_namespace: eduk8s
  contour_tls_secret: eduk8s-cert-tls
harbor:
  adminPassword: Harbor12345
  diskSize: 50Gi
gitea:
  adminPassword: <PASSWORD>
registry:
  dockerhub: docker.io
git:
  account: tanzu-end-to-end
  branch: main
  #! Optionally, you can specify a Github token. This will be used by Harbor's Trivy scanner to avoid hitting rate limites
  #!   gitHubToken: <token>

