apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap-workshop
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    registration:
      type: one-step
      enabled: true
    updates:
      workshop: true
    sessions:
      maximum: 15
  workshops:
    - name: tap-overview
      expires: 120m
      orphaned: 20m
      capacity: 20
      reserved: 1
